/* =====================================================================
   DE MOESTUIN, gegevens: groenten, fruit, kruiden (NL, ervaringskennis)
   maanden: 1=jan .. 12=dec   loc: 'openlucht'|'kas'|'beide'   voor=voorzaaien
   ===================================================================== */
const MND=['jan','feb','mrt','apr','mei','jun','jul','aug','sep','okt','nov','dec'];
const DATA=[
/* GROENTEN */
{id:'tomaat',naam:'Tomaat',lat:'Solanum lycopersicum',type:'groente',fam:'vrucht',loc:'beide',zon:'zon',water:'hoog',afstand:50,rij:70,diepte:1,voor:[2,3,4],zaai:[],uit:[5,6],oogst:[7,8,9,10],duur:90,moeite:'gemiddeld',vrienden:['basilicum','O.I. kers','peterselie','wortel','ui','knoflook','selderij','sla','goudsbloem','prei','borage','bieslook','munt','oregano','asperge','paprika','kruisbes'],vijanden:['aardappel','venkel','kool','doperwt','spruitkool','koolrabi','bloemkool','mais','boerenkool','braam','framboos','broccoli','komkommer'],tip:'Zet basilicum ernaast: dat weert de witte vlieg.',zorg:'Neem okselscheuten (dieven) weg en geef onderaan water, niet over het blad, zo voorkom je meeldauw.',rassen:[{naam:'Moneymaker',type:'ronde tomaat',kort:'Betrouwbare klassieker met veel middelgrote vruchten.'},{naam:'Coeur de Boeuf',type:'vleestomaat',kort:'Grote, vlezige vruchten met weinig zaad, ideaal op brood.'},{naam:'Sungold',type:'kerstomaat',kort:'Zeer zoete oranje snoeptomaatjes, rijk dragend.'},{naam:'Roma',type:'roma- / pruimtomaat',kort:'Stevig vruchtvlees, perfect voor saus en passata.'},{naam:'Black Cherry',type:'kerstomaat',kort:'Donkere kerstomaat met een volle, zoete smaak.'},{naam:'Tigerella',type:'gestreepte tomaat',kort:'Rood-geel gestreept en fris van smaak.'}]},
{id:'komkommer',naam:'Komkommer',lat:'Cucumis sativus',type:'groente',fam:'vrucht',loc:'beide',zon:'zon',water:'hoog',afstand:40,rij:80,diepte:2,voor:[3,4],zaai:[],uit:[5,6],oogst:[7,8,9],duur:65,moeite:'gemiddeld',vrienden:['stamboon','mais','sla','doperwt','dille','ui','koriander','radijs','knoflook','venkel'],vijanden:['aardappel','tomaat','courgette','salie'],tip:'Houdt van warmte en een vochtige, rijke bodem.',zorg:'Geef gelijkmatig water en bied klimsteun; pluk regelmatig om de plant productief te houden.',rassen:[{naam:'Marketmore',type:'slangkomkommer',kort:'Betrouwbare komkommer voor buiten.'},{naam:'Citroenkomkommer',type:'ronde komkommer',kort:'Gele, ronde en milde vruchtjes.'},{naam:'Iznik',type:'snackkomkommer',kort:'Kleine, knapperige mini-komkommertjes.'},{naam:'Bonbon',type:'kaskomkommer',kort:'Zelfbestuivend en betrouwbaar in de kas.'}]},
{id:'courgette',naam:'Courgette',lat:'Cucurbita pepo',type:'groente',fam:'vrucht',loc:'openlucht',zon:'zon',water:'hoog',afstand:80,rij:100,diepte:2,voor:[4],zaai:[5],uit:[5,6],oogst:[7,8,9],duur:50,moeite:'makkelijk',vrienden:['mais','stamboon','O.I. kers','bonenkruid','borage','basilicum'],vijanden:['aardappel','komkommer'],tip:'O.I. kers ernaast lokt luis weg van het blad.',zorg:'Geef veel ruimte en voeding. Oogst jong en vaak, anders stopt de plant met nieuwe vruchten.',rassen:[{naam:'Black Beauty',type:'groene courgette',kort:'Donkergroene klassieker.'},{naam:'Gold Rush',type:'gele courgette',kort:'Felgele, decoratieve vruchten.'},{naam:'Ronde de Nice',type:'ronde courgette',kort:'Bolvormig, leuk om te vullen.'},{naam:'Tromboncino',type:'slingercourgette',kort:'Lange, gebogen vruchten; klimt graag.'}]},
{id:'pompoen',naam:'Pompoen',lat:'Cucurbita maxima',type:'groente',fam:'vrucht',loc:'openlucht',zon:'zon',water:'hoog',afstand:120,rij:150,diepte:3,voor:[4],zaai:[],uit:[5,6],oogst:[9,10],duur:110,moeite:'makkelijk',vrienden:['mais','stamboon','O.I. kers'],vijanden:['aardappel'],tip:'Klassieke Drie Zusters: mais + stokboon + pompoen.',zorg:'Veel ruimte en mest. Leg rijpende vruchten op een plankje tegen rot.',rassen:[{naam:'Hokkaido',type:'oranje pompoen',kort:'Kastanjesmaak, de schil kun je meeeten.'},{naam:'Butternut',type:'flespompoen',kort:'Zoet en nootachtig, goed houdbaar.'},{naam:'Spaghetti',type:'spaghettipompoen',kort:'Vruchtvlees valt na koken in sliertjes uiteen.'},{naam:'Crown Prince',type:'blauwe pompoen',kort:'Grijsblauwe schil, heel zoet vruchtvlees.'},{naam:'Patisson',type:'schotelpompoen',kort:'Kleine, schotelvormige vruchten.'}]},
{id:'paprika',naam:'Paprika',lat:'Capsicum annuum',type:'groente',fam:'vrucht',loc:'kas',zon:'zon',water:'matig',afstand:40,rij:50,diepte:1,voor:[2,3],zaai:[],uit:[5,6],oogst:[7,8,9,10],duur:100,moeite:'gemiddeld',vrienden:['basilicum','ui','wortel','tomaat','peterselie','aubergine','oregano'],vijanden:['venkel','kool','doperwt'],tip:'Wil het warm, in de kas of tegen een warme muur.',zorg:'Geef steun en gelijkmatig water. Eerste bloem wegknijpen geeft een stevigere plant.',rassen:[{naam:'California Wonder',type:'blokpaprika',kort:'Dikwandig, groen naar rood, de klassieker.'},{naam:'Corno di Toro',type:'puntpaprika',kort:'Zoete, langwerpige paprika, top van de grill.'},{naam:'Friggitello',type:'bakpaprika',kort:'Klein en mild, lekker even aanbakken.'},{naam:'Jalapeno',type:'middelhete peper',kort:'Stevige, matig pittige peper.'},{naam:'Habanero',type:'hete peper',kort:'Zeer pittig, voor de liefhebber.'}]},
{id:'aardappel',naam:'Aardappel',lat:'Solanum tuberosum',type:'groente',fam:'knol',loc:'openlucht',zon:'zon',water:'matig',afstand:35,rij:65,diepte:10,voor:[],zaai:[],uit:[3,4],oogst:[6,7,8,9],duur:100,moeite:'makkelijk',vrienden:['stamboon','kool','mais','spinazie','mierikswortel','tuinboon'],vijanden:['tomaat','komkommer','pompoen','selderij','braam','framboos','courgette'],tip:'Wissel jaarlijks van plek tegen aardappelmoeheid.',zorg:'Aanaarden zodra het loof boven staat. Let in een natte zomer op de phytophthora (aardappelziekte).',rassen:[{naam:'Charlotte',type:'vastkokend',kort:'Fijne salade- en krielaardappel.'},{naam:'Nicola',type:'vastkokend',kort:'Romig en breed inzetbaar.'},{naam:'Bintje',type:'bloemig',kort:'Klassieker voor friet en puree.'},{naam:'Frieslander',type:'vastkokend',kort:'Vroege, smaakvolle aardappel.'},{naam:'Sarpo Mira',type:'bloemig',kort:'Sterk tegen de aardappelziekte.'}]},
{id:'wortel',naam:'Wortel / peen',lat:'Daucus carota',type:'groente',fam:'wortel',loc:'openlucht',zon:'zon',water:'matig',afstand:5,rij:25,diepte:1,voor:[],zaai:[3,4,5,6,7],uit:[],oogst:[6,7,8,9,10,11],duur:80,moeite:'makkelijk',vrienden:['ui','prei','knoflook','sla','radijs','doperwt','rucola','salie','bieslook','tomaat','peterselie','rozemarijn','witlof','paprika'],vijanden:['dille','venkel','biet','pastinaak','anijs'],tip:'Ui ernaast verwart de wortelvlieg.',zorg:'Zaai in losse, steenvrije grond en dun op tijd uit, anders blijven de wortels klein.',rassen:[{naam:'Nantes',type:'stompe wortel',kort:'Zoete, knapperige zomerwortel.'},{naam:'Flakkeese',type:'bewaarwortel',kort:'Grote winterwortel, lang houdbaar.'},{naam:'Amsterdamse Bak',type:'vroege wortel',kort:'Fijne, vroege worteltjes.'},{naam:'Purple Haze',type:'paarse wortel',kort:'Paars van buiten, oranje van binnen.'},{naam:'Parijse Markt',type:'ronde wortel',kort:'Bolronde worteltjes, ook in een pot.'}]},
{id:'ui',naam:'Ui',lat:'Allium cepa',type:'groente',fam:'ui',loc:'openlucht',zon:'zon',water:'laag',afstand:10,rij:25,diepte:2,voor:[],zaai:[3],uit:[3,4],oogst:[7,8],duur:120,moeite:'makkelijk',vrienden:['wortel','biet','sla','aardbei','kool','tomaat','andijvie','prei','koolrabi','paprika','broccoli','spinazie','pastinaak','boerenkool','snijbiet','braam','selderij','rode & zwarte bes','spruitkool','bloemkool','kamille','witlof','komkommer','dille','framboos'],vijanden:['stamboon','doperwt','tuinboon','asperge'],tip:'De uiengeur houdt veel plagen op afstand.',zorg:'Houd onkruidvrij en laat tegen het einde droog afrijpen voor langere bewaring.',rassen:[{naam:'Stuttgarter Riesen',type:'gele bewaarui',kort:'Betrouwbaar uit plantuitjes.'},{naam:'Red Baron',type:'rode ui',kort:'Milde, kleurige ui.'},{naam:'Sturon',type:'gele ui',kort:'Grote, goed houdbare ui.'},{naam:'Zilveruitje',type:'zilverui',kort:'Klein wit uitje om in te maken.'}]},
{id:'knoflook',naam:'Knoflook',lat:'Allium sativum',type:'groente',fam:'ui',loc:'openlucht',zon:'zon',water:'laag',afstand:15,rij:25,diepte:5,voor:[],zaai:[],uit:[10,11,2,3],oogst:[6,7],duur:240,moeite:'makkelijk',vrienden:['wortel','tomaat','aardbei','komkommer','rozen','rode & zwarte bes','rabarber','pastinaak','druif','biet','framboos','braam'],vijanden:['stamboon','doperwt','kool','tuinboon','asperge'],tip:'In het najaar poten geeft de grootste bollen.',zorg:'Knip bloeistengels (look) weg zodat de plant in de bol investeert.',rassen:[{naam:'Thermidrome',type:'witte knoflook',kort:'Zachte soort (softneck), goed houdbaar.'},{naam:'Germidour',type:'paarse knoflook',kort:'Aromatisch, voor najaarsplanting.'}]},
{id:'prei',naam:'Prei',lat:'Allium porrum',type:'groente',fam:'ui',loc:'openlucht',zon:'zon',water:'matig',afstand:15,rij:30,diepte:1,voor:[2,3,4],zaai:[],uit:[6,7],oogst:[9,10,11,12,1,2],duur:150,moeite:'gemiddeld',vrienden:['wortel','selderij','ui','tomaat','kool','andijvie','venkel'],vijanden:['stamboon','doperwt','biet'],tip:'Plant diep in een pootgat voor een lang wit deel.',zorg:'Aanaarden tijdens de groei maakt het witte, malse deel langer.',rassen:[{naam:'Herfstreuzen',type:'herfstprei',kort:'Snelle, milde prei voor de herfst.'},{naam:'Bleu de Solaise',type:'winterprei',kort:'Vorstbestendig en blauwgroen.'}]},
{id:'sla',naam:'Sla',lat:'Lactuca sativa',type:'groente',fam:'blad',loc:'beide',zon:'halfschaduw',water:'matig',afstand:25,rij:30,diepte:1,voor:[3],zaai:[4,5,6,7,8],uit:[4,5,6,7,8],oogst:[5,6,7,8,9,10],duur:50,moeite:'makkelijk',vrienden:['wortel','radijs','komkommer','ui','aardbei','biet','tuinboon','snijbiet','pastinaak','rucola','koolrabi','dille','tomaat','doperwt','kervel'],vijanden:['peterselie','andijvie'],tip:'Zaai om de 2–3 weken bij voor een doorlopende oogst.',zorg:'Houd vochtig en oogst voor de hitte, anders schiet de sla door en wordt bitter.',rassen:[{naam:'Appia',type:'botersla',kort:'Zachte, botzachte krop.'},{naam:'Eikenbladsla',type:'pluksla',kort:'Pluk blad voor blad, mooi gerand.'},{naam:'Lollo Rossa',type:'pluksla',kort:'Gekrulde, rode sla.'},{naam:'IJsbergsla',type:'kropsla',kort:'Knapperige, stevige krop.'},{naam:'Little Gem',type:'bindsla',kort:'Stevige, zoete hartjes.'}]},
{id:'spinazie',naam:'Spinazie',lat:'Spinacia oleracea',type:'groente',fam:'blad',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:10,rij:25,diepte:2,voor:[],zaai:[3,4,8,9],uit:[],oogst:[5,6,10,11],duur:45,moeite:'makkelijk',vrienden:['aardbei','stamboon','kool','radijs','ui','koriander','tuinboon','koolrabi','aardappel'],vijanden:['biet','snijbiet'],tip:'Een voorjaars- en najaarsgewas; schiet door in de zomerhitte.',zorg:'Geef bodembedekking en water in droge periodes om doorschieten te remmen.'},
{id:'radijs',naam:'Radijs',lat:'Raphanus sativus',type:'groente',fam:'wortel',loc:'beide',zon:'halfschaduw',water:'matig',afstand:4,rij:15,diepte:1,voor:[],zaai:[3,4,5,6,7,8,9],uit:[],oogst:[4,5,6,7,8,9,10],duur:28,moeite:'makkelijk',vrienden:['wortel','sla','komkommer','doperwt','O.I. kers','pastinaak','kervel','spinazie'],vijanden:['hysop'],tip:'In 4 weken klaar, ideaal als markeerzaad tussen trage gewassen.',zorg:'Houd constant vochtig, anders worden ze houtig en scherp.',rassen:[{naam:'Cherry Belle',type:'ronde radijs',kort:'Snelle, ronde rode radijs.'},{naam:'French Breakfast',type:'langwerpige radijs',kort:'Mild, rood met een witte punt.'},{naam:'Rettich',type:'winterradijs',kort:'Lange witte radijs voor het najaar.'}]},
{id:'biet',naam:'Rode biet',lat:'Beta vulgaris',type:'groente',fam:'wortel',loc:'openlucht',zon:'zon',water:'matig',afstand:10,rij:30,diepte:2,voor:[],zaai:[4,5,6],uit:[],oogst:[7,8,9,10],duur:90,moeite:'makkelijk',vrienden:['ui','kool','sla','koolrabi','knoflook','rucola','bloemkool','boerenkool','snijbiet','broccoli'],vijanden:['stamboon','spinazie','wortel','pastinaak','prei','mais'],tip:'Het loof is eetbaar als snijbiet.',zorg:'Dun uit tot één plant per kluitje; elk zaadje bevat meerdere kiemen.',rassen:[{naam:'Boltardy',type:'ronde kroot',kort:'Klassieker die niet snel doorschiet.'},{naam:'Chioggia',type:'ringbiet',kort:'Rood-wit geringd vruchtvlees.'},{naam:'Cylindra',type:'lange biet',kort:'Cilindrisch, handig in plakjes.'},{naam:'Golden',type:'gele biet',kort:'Mild en zoet, kleurt niet af.'}]},
{id:'boon',naam:'Stam- / stokboon',lat:'Phaseolus vulgaris',type:'groente',fam:'peul',loc:'openlucht',zon:'zon',water:'matig',afstand:15,rij:50,diepte:3,voor:[],zaai:[5,6],uit:[],oogst:[7,8,9],duur:60,moeite:'makkelijk',vrienden:['mais','komkommer','aardappel','kool','aardbei','bonenkruid','selderij','pompoen','andijvie','rabarber','aubergine','rozemarijn','O.I. kers','courgette','spinazie'],vijanden:['ui','knoflook','prei','venkel','biet'],tip:'Vlinderbloemigen brengen stikstof in de grond.',zorg:'Niet voor half mei zaaien, bonen zijn koudegevoelig. Stokbonen klimmen langs bonenstaken.',rassen:[{naam:'Maxi',type:'stamslaboon',kort:'Lage boon zonder steun, fijne sperziebonen.'},{naam:'Neckarkonigin',type:'stokslaboon',kort:'Klimt en geeft een lange oogst.'},{naam:'Pronkboon',type:'pronkboon',kort:'Rode bloemen en grote bonen.'},{naam:'Borlotti',type:'spek- / droogboon',kort:'Gevlekte bonen, lekker om te drogen.'}]},
{id:'doperwt',naam:'Doperwt',lat:'Pisum sativum',type:'groente',fam:'peul',loc:'openlucht',zon:'zon',water:'matig',afstand:5,rij:40,diepte:4,voor:[],zaai:[3,4,5],uit:[],oogst:[6,7],duur:90,moeite:'makkelijk',vrienden:['wortel','radijs','komkommer','mais','sla','pastinaak'],vijanden:['ui','knoflook','prei','tomaat','paprika'],tip:'Zaai vroeg; de plant verdraagt nog lichte vorst.',zorg:'Zet takken of gaas neer waar de erwt langs kan klimmen.',rassen:[{naam:'Kelvedon Wonder',type:'doperwt',kort:'Klassieke dop-erwt.'},{naam:'Suikererwt',type:'peul',kort:'Hele peul eetbaar en zoet.'},{naam:'Kapucijner',type:'kapucijner',kort:'Bruine droogerwt, oud-Hollands.'}]},
{id:'kool',naam:'Kool',lat:'Brassica oleracea',type:'groente',fam:'kool',loc:'openlucht',zon:'zon',water:'hoog',afstand:50,rij:60,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[8,9,10,11],duur:100,moeite:'gemiddeld',vrienden:['aardappel','selderij','ui','biet','spinazie','dille','kamille','andijvie','prei','goudsbloem','hysop','oregano','tijm','salie','munt','rabarber','rozemarijn','O.I. kers','stamboon'],vijanden:['tomaat','aardbei','paprika','knoflook'],tip:'Sterk geurende kruiden verwarren het koolwitje.',zorg:'Plant stevig en leg een kraagje rond de stam tegen de koolvlieg; net erover houdt rupsen weg.'},
{id:'selderij',naam:'Selderij',lat:'Apium graveolens',type:'groente',fam:'blad',loc:'openlucht',zon:'halfschaduw',water:'hoog',afstand:30,rij:40,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[8,9,10],duur:120,moeite:'gemiddeld',vrienden:['kool','prei','tomaat','stamboon','ui','spruitkool','bloemkool','boerenkool','broccoli'],vijanden:['aardappel','peterselie','pastinaak'],tip:'Wil een vochtige, voedzame standplaats.',zorg:'Laat nooit uitdrogen; selderij heeft door het hele seizoen veel water nodig.'},
{id:'mais',naam:'Mais',lat:'Zea mays',type:'groente',fam:'vrucht',loc:'openlucht',zon:'zon',water:'matig',afstand:30,rij:40,diepte:3,voor:[4],zaai:[5],uit:[5,6],oogst:[8,9],duur:90,moeite:'makkelijk',vrienden:['stokboon','pompoen','komkommer','doperwt','courgette','aardappel'],vijanden:['tomaat','biet'],tip:'Plant in een blok i.p.v. een rij voor goede bestuiving.',zorg:'Geeft schaduw en klimsteun aan bonen; geef in droge tijden extra water bij de kolfvorming.'},
{id:'andijvie',naam:'Andijvie',lat:'Cichorium endivia',type:'groente',fam:'blad',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:30,rij:35,diepte:1,voor:[],zaai:[5,6,7],uit:[6,7,8],oogst:[8,9,10],duur:70,moeite:'makkelijk',vrienden:['prei','ui','venkel','kool','boon'],vijanden:['sla'],tip:'Bleek de struik enkele dagen voor een mildere smaak.',zorg:'Houd vochtig; bij droogte wordt andijvie bitter en schiet door.',rassen:[{naam:'Frisee',type:'krulandijvie',kort:'Gekruld en licht bitter.'},{naam:'Escariol',type:'brede andijvie',kort:'Brede bladeren, milder van smaak.'}]},
{id:'venkel',naam:'Venkel (knol)',lat:'Foeniculum vulgare',type:'groente',fam:'blad',loc:'openlucht',zon:'zon',water:'matig',afstand:30,rij:40,diepte:1,voor:[],zaai:[5,6,7],uit:[],oogst:[9,10,11],duur:90,moeite:'gemiddeld',vrienden:['komkommer','andijvie','prei'],vijanden:['tomaat','boon','wortel','paprika','koriander'],tip:'Een echte einzelgänger: geef venkel een eigen plek.',zorg:'Geef gelijkmatig water tegen voortijdig schieten; aanaarden maakt de knol witter.'},
{id:'pastinaak',naam:'Pastinaak',lat:'Pastinaca sativa',type:'groente',fam:'wortel',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:15,rij:30,diepte:2,voor:[],zaai:[3,4,5],uit:[],oogst:[10,11,12,1,2],duur:160,moeite:'gemiddeld',vrienden:['ui','knoflook','radijs','sla','doperwt'],vijanden:['wortel','selderij','biet'],tip:'Smaakt zoeter na de eerste nachtvorst.',zorg:'Kiemt traag (3–4 weken), geduld en vochtig houden. Gebruik vers zaad.'},
{id:'mierikswortel',naam:'Mierikswortel',lat:'Armoracia rusticana',type:'groente',fam:'wortel',loc:'openlucht',zon:'zon',water:'matig',afstand:40,rij:50,diepte:8,voor:[],zaai:[],uit:[3,4],oogst:[10,11,12],duur:0,moeite:'makkelijk',vrienden:['aardappel'],vijanden:[],tip:'Aan de rand van het aardappelbed zou het de knollen gezonder houden.',zorg:'Woekert flink: zet in een ingegraven pot of bak om uitbreiding te beperken.'},
{id:'asperge',naam:'Asperge',lat:'Asparagus officinalis',type:'groente',fam:'blad',loc:'openlucht',zon:'zon',water:'matig',afstand:40,rij:120,diepte:20,voor:[],zaai:[],uit:[3,4],oogst:[4,5,6],duur:0,moeite:'gemiddeld',vrienden:['peterselie','tomaat','dille'],vijanden:['ui','knoflook'],tip:'Peterselie en tomaat zijn klassieke aspergeburen.',zorg:'Meerjarig bed (15+ jaar). Oogst pas vanaf het derde jaar, tot half juni.'},
{id:'aubergine',naam:'Aubergine',lat:'Solanum melongena',type:'groente',fam:'vrucht',loc:'kas',zon:'zon',water:'hoog',afstand:50,rij:60,diepte:1,voor:[2,3],zaai:[],uit:[5,6],oogst:[7,8,9,10],duur:110,moeite:'gemiddeld',vrienden:['tijm','boon','paprika'],vijanden:[],tip:'Wil het echt warm: kas of serre.',zorg:'Steun de plant en houd de grond gelijkmatig vochtig.',rassen:[{naam:'Black Beauty',type:'klassieke aubergine',kort:'Grote donkerpaarse vruchten.'},{naam:'Violetta Lunga',type:'lange aubergine',kort:'Slanke, milde vruchten.'},{naam:'Ophelia',type:'mini-aubergine',kort:'Kleine vruchten, fijn voor pot en kas.'}]},
{id:'koolrabi',naam:'Koolrabi',lat:'Brassica oleracea Gongylodes',type:'groente',fam:'kool',loc:'beide',zon:'zon',water:'matig',afstand:25,rij:30,diepte:1,voor:[3],zaai:[4,5,6,7],uit:[4,5,6,7,8],oogst:[6,7,8,9,10],duur:60,moeite:'makkelijk',vrienden:['sla','biet','ui','spinazie'],vijanden:['tomaat'],tip:'Snelle koolsoort; oogst jong en mals voor hij houtig wordt.',zorg:'Gelijkmatig water houdt de knol zacht.'},
{id:'bloemkool',naam:'Bloemkool',lat:'Brassica oleracea Botrytis',type:'groente',fam:'kool',loc:'openlucht',zon:'zon',water:'hoog',afstand:50,rij:60,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[7,8,9,10],duur:110,moeite:'gemiddeld',vrienden:['selderij','ui','biet','dille','kamille'],vijanden:['tomaat','aardbei'],tip:'Vouw de bladeren over de witte kool tegen verkleuring.',zorg:'Veel en regelmatig water; een droge periode geeft kleine kolen.',rassen:[{naam:'Neckarperle',type:'witte bloemkool',kort:'Betrouwbare, fijne kool.'},{naam:'Graffiti',type:'paarse bloemkool',kort:'Paars van kleur, decoratief.'},{naam:'Romanesco',type:'torentjeskool',kort:'Groene punten in spiraalvorm.'}]},
{id:'broccoli',naam:'Broccoli',lat:'Brassica oleracea Italica',type:'groente',fam:'kool',loc:'openlucht',zon:'zon',water:'hoog',afstand:50,rij:60,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[7,8,9,10],duur:90,moeite:'gemiddeld',vrienden:['selderij','ui','biet','kamille'],vijanden:['tomaat','aardbei'],tip:'Na de hoofdkool blijven de zijscheuten doorkomen.',zorg:'Oogst de hoofdkool voor de bloemknoppen opengaan.'},
{id:'boerenkool',naam:'Boerenkool',lat:'Brassica oleracea Sabellica',type:'groente',fam:'kool',loc:'openlucht',zon:'zon',water:'matig',afstand:50,rij:60,diepte:1,voor:[5,6],zaai:[],uit:[6,7],oogst:[11,12,1,2],duur:150,moeite:'makkelijk',vrienden:['ui','biet','selderij','kamille'],vijanden:['tomaat'],tip:'Smaakt zachter na de eerste nachtvorst.',zorg:'Stevig planten; de plant verdraagt vorst prima.',rassen:[{naam:'Westlandse Herfst',type:'halflange boerenkool',kort:'Klassieke, gekrulde boerenkool.'},{naam:'Nero di Toscana',type:'palmkool (cavolo nero)',kort:'Donkere, gladde Italiaanse kool.'}]},
{id:'spruitkool',naam:'Spruitkool',lat:'Brassica oleracea Gemmifera',type:'groente',fam:'kool',loc:'openlucht',zon:'zon',water:'matig',afstand:60,rij:70,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[10,11,12,1],duur:180,moeite:'gemiddeld',vrienden:['ui','selderij','kamille'],vijanden:['tomaat','aardbei'],tip:'Lang seizoen; oogst de spruiten van onder naar boven.',zorg:'Druk stevig aan en staak eventueel aan tegen windworp.'},
{id:'witlof',naam:'Witlof',lat:'Cichorium intybus',type:'groente',fam:'blad',loc:'openlucht',zon:'zon',water:'matig',afstand:12,rij:30,diepte:1,voor:[],zaai:[5,6],uit:[],oogst:[10,11],duur:150,moeite:'gemiddeld',vrienden:['wortel','ui'],vijanden:[],tip:'Rooi de wortels in het najaar en trek de lof binnen in het donker.',zorg:'Een magere grond geeft rechtere wortels om te forceren.'},
{id:'snijbiet',naam:'Snijbiet',lat:'Beta vulgaris Cicla',type:'groente',fam:'blad',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:25,rij:35,diepte:2,voor:[],zaai:[4,5,6],uit:[],oogst:[6,7,8,9,10,11],duur:60,moeite:'makkelijk',vrienden:['biet','sla','ui'],vijanden:['spinazie'],tip:'Oogst blad voor blad, dan groeit de plant gewoon door.',zorg:'Verdraagt schaduw en blijft lang doorsnijden.'},
{id:'tuinboon',naam:'Tuinboon',lat:'Vicia faba',type:'groente',fam:'peul',loc:'openlucht',zon:'zon',water:'matig',afstand:15,rij:45,diepte:5,voor:[],zaai:[2,3,11],uit:[],oogst:[6,7],duur:100,moeite:'makkelijk',vrienden:['aardappel','sla','spinazie'],vijanden:['ui','knoflook'],tip:'Zaai vroeg, of in november voor een oogst in juni.',zorg:'Top de plant bij luis: de zwarte boneluis zit in de top.',rassen:[{naam:'Witkiem',type:'tuinboon',kort:'Vroege, betrouwbare tuinboon.'},{naam:'Driemaal Wit',type:'tuinboon',kort:'Veel bonen per peul.'}]},
{id:'rucola',naam:'Rucola',lat:'Eruca sativa',type:'groente',fam:'blad',loc:'beide',zon:'halfschaduw',water:'matig',afstand:10,rij:15,diepte:1,voor:[],zaai:[3,4,5,6,7,8,9],uit:[],oogst:[4,5,6,7,8,9,10],duur:35,moeite:'makkelijk',vrienden:['sla','biet','wortel'],vijanden:[],tip:'Snel klaar; zaai om de paar weken bij.',zorg:'Schiet door in hitte; oogst jong voor een milde smaak.'},
/* FRUIT */
{id:'aardbei',naam:'Aardbei',lat:'Fragaria × ananassa',type:'fruit',fam:'fruit',loc:'openlucht',zon:'zon',water:'matig',afstand:30,rij:40,diepte:0,voor:[],zaai:[],uit:[8,9,3,4],oogst:[6,7],duur:0,moeite:'makkelijk',vrienden:['sla','spinazie','ui','knoflook','bieslook','borage','stamboon'],vijanden:['kool','spruitkool','bloemkool','broccoli'],tip:'Plant in het najaar voor een oogst het jaar erop.',zorg:'Leg stro onder de vruchten tegen rot en verwijder uitlopers die je niet wilt.',rassen:[{naam:'Elsanta',type:'junidrager',kort:'Grote, zoete aardbei, de klassieker.'},{naam:'Korona',type:'junidrager',kort:'Zeer aromatisch en zacht.'},{naam:'Mara des Bois',type:'doordrager',kort:'Bosaardbei-aroma, oogst de hele zomer.'},{naam:'Ostara',type:'doordrager',kort:'Lange oogst tot in de herfst.'},{naam:'Sonata',type:'junidrager',kort:'Stevig en zoet.'}]},
{id:'framboos',naam:'Framboos',lat:'Rubus idaeus',type:'fruit',fam:'struik',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:50,rij:150,diepte:0,voor:[],zaai:[],uit:[11,12,2,3],oogst:[6,7,8,9,10],duur:0,moeite:'makkelijk',vrienden:['knoflook','ui','goudsbloem','bieslook'],vijanden:['aardappel','tomaat','braam dichtbij'],tip:'Alliums eromheen weren schimmel.',zorg:'Zomer- en herfstframbozen snoei je anders: zet een steundraad en knip uitgedragen scheuten weg.',rassen:[{naam:'Glen Ample',type:'zomerframboos',kort:'Grote vruchten, stekelloze stengels.'},{naam:'Autumn Bliss',type:'herfstframboos',kort:'Draagt in de nazomer, makkelijk te snoeien.'},{naam:'Fallgold',type:'gele herfstframboos',kort:'Zoete, gele vruchten.'}]},
{id:'braam',naam:'Braam',lat:'Rubus fruticosus',type:'fruit',fam:'struik',loc:'openlucht',zon:'zon',water:'matig',afstand:150,rij:200,diepte:0,voor:[],zaai:[],uit:[11,3],oogst:[8,9,10],duur:0,moeite:'makkelijk',vrienden:['knoflook','ui','goudsbloem'],vijanden:['framboos dichtbij','aardappel','tomaat'],tip:'Houd bessen uit de buurt van nachtschades zoals tomaat en aardappel.',zorg:'Leid de ranken langs draden en knip gedragen ranken na de oogst weg.',rassen:[{naam:'Thornless Evergreen',type:'doornloze braam',kort:'Geen stekels en productief.'},{naam:'Loch Ness',type:'doornloze braam',kort:'Grote, zoete vruchten.'}]},
{id:'bes',naam:'Rode & zwarte bes',lat:'Ribes',type:'fruit',fam:'struik',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:150,rij:150,diepte:0,voor:[],zaai:[],uit:[11,12,2,3],oogst:[7,8],duur:0,moeite:'makkelijk',vrienden:['ui','knoflook','bieslook','goudsbloem'],vijanden:['tomaat dichtbij'],tip:'Alliums eronder verminderen meeldauw.',zorg:'Dun oud hout in de winter uit zodat licht en lucht erbij kunnen.',rassen:[{naam:'Jonkheer van Tets',type:'rode bes',kort:'Vroege, rijk dragende tros.'},{naam:'Ben Sarek',type:'zwarte bes',kort:'Compacte struik, veel vitamine C.'},{naam:'Witte Hollander',type:'witte bes',kort:'Milde, zoete tros.'}]},
{id:'kruisbes',naam:'Kruisbes',lat:'Ribes uva-crispa',type:'fruit',fam:'struik',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:150,rij:150,diepte:0,voor:[],zaai:[],uit:[11,3],oogst:[7],duur:0,moeite:'gemiddeld',vrienden:['tomaat','bieslook','kervel'],vijanden:[],tip:'Bieslook eromheen helpt tegen Amerikaanse meeldauw.',zorg:'Houd het hart open door snoei; dat beperkt meeldauw aanzienlijk.',rassen:[{naam:'Hinnonmaki Rood',type:'rode kruisbes',kort:'Zoet en redelijk meeldauwbestendig.'},{naam:'Invicta',type:'groene kruisbes',kort:'Productief en ziekteresistent.'}]},
{id:'blauwebes',naam:'Blauwe bes',lat:'Vaccinium',type:'fruit',fam:'struik',loc:'openlucht',zon:'zon',water:'hoog',afstand:120,rij:120,diepte:0,voor:[],zaai:[],uit:[10,11,3],oogst:[7,8],duur:0,moeite:'gemiddeld',vrienden:['dennenstrooisel','rododendron'],vijanden:['kalkminnende planten'],tip:'Wil zure grond (pH 4–5): zet apart, los van de groenten.',zorg:'Gebruik potgrond voor zuurminnaars en geef bij voorkeur regenwater.',rassen:[{naam:'Bluecrop',type:'blauwe bes',kort:'Betrouwbaar met grote vruchten.'},{naam:'Duke',type:'vroege blauwe bes',kort:'Rijpt vroeg in het seizoen.'},{naam:'Patriot',type:'compacte blauwe bes',kort:'Geschikt voor een pot.'}]},
{id:'druif',naam:'Druif',lat:'Vitis vinifera',type:'fruit',fam:'fruit',loc:'beide',zon:'zon',water:'laag',afstand:150,rij:150,diepte:0,voor:[],zaai:[],uit:[3,4,11],oogst:[9,10],duur:0,moeite:'gemiddeld',vrienden:['hysop','bieslook','look','geranium'],vijanden:['kool dichtbij'],tip:'Tegen een warme zuidmuur of in de kas rijpt de druif het best.',zorg:'Snoei in de winterrust (december–januari); in de zomer scheuten indammen.',rassen:[{naam:'Boskoop Glory',type:'blauwe druif',kort:'Betrouwbaar buiten, ook in natte zomers.'},{naam:'Muscat bleu',type:'blauwe druif',kort:'Aromatisch en vorstbestendig.'},{naam:'Vroege van der Laan',type:'witte druif',kort:'Vroeg rijpend, weinig pitten.'}]},
{id:'rabarber',naam:'Rabarber',lat:'Rheum rhabarbarum',type:'fruit',fam:'blad',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:100,rij:100,diepte:0,voor:[],zaai:[],uit:[10,11,3],oogst:[4,5,6],duur:0,moeite:'makkelijk',vrienden:['kool','knoflook','boon'],vijanden:[],tip:'Oogst niet in het eerste jaar; het blad is giftig, alleen de steel is eetbaar.',zorg:'Geef in het najaar compost en oogst tot uiterlijk juni, daarna laten herstellen.',rassen:[{naam:'Timperley Early',type:'vroege rabarber',kort:'Heel vroeg te oogsten en mild.'},{naam:'Victoria',type:'rabarber',kort:'Klassieker met stevige stelen.'}]},
/* KRUIDEN */
{id:'basilicum',naam:'Basilicum',lat:'Ocimum basilicum',type:'kruid',fam:'kruid',loc:'kas',zon:'zon',water:'matig',afstand:20,rij:25,diepte:1,voor:[3,4],zaai:[],uit:[5,6],oogst:[6,7,8,9],duur:60,moeite:'makkelijk',vrienden:['tomaat','paprika','courgette'],vijanden:[],tip:'Weert witte vlieg en muggen, en versterkt de smaak van tomaat.',zorg:'Houd warm en niet te nat; top regelmatig zodat de plant vol blijft.',rassen:[{naam:'Genovese',type:'gewone basilicum',kort:'De klassieker voor pesto en pasta.'},{naam:'Rode basilicum',type:'rode basilicum',kort:'Paarsrood blad, decoratief.'},{naam:'Citroenbasilicum',type:'citroenbasilicum',kort:'Frisse citrustoon.'},{naam:'Thaise basilicum',type:'Thaise basilicum',kort:'Anijsachtig, voor wokgerechten.'}]},
{id:'bieslook',naam:'Bieslook',lat:'Allium schoenoprasum',type:'kruid',fam:'kruid',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:20,rij:20,diepte:1,voor:[],zaai:[3,4],uit:[],oogst:[4,5,6,7,8,9,10],duur:60,moeite:'makkelijk',vrienden:['wortel','tomaat','aardbei','fruit','rode & zwarte bes','kruisbes','druif','framboos'],vijanden:[],tip:'Weert luis en meeldauw, een topbuur voor fruit.',zorg:'Vaste plant: deel de pol om de paar jaar zodat hij krachtig blijft.'},
{id:'bonenkruid',naam:'Bonenkruid',lat:'Satureja hortensis',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'laag',afstand:20,rij:25,diepte:1,voor:[],zaai:[5],uit:[],oogst:[7,8,9],duur:70,moeite:'makkelijk',vrienden:['boon','courgette'],vijanden:[],tip:'Beschermt bonen tegen de zwarte luis en verbetert hun smaak.',zorg:'Zaai naast de bonen; houdt van een zonnige, niet te natte plek.'},
{id:'dille',naam:'Dille',lat:'Anethum graveolens',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'matig',afstand:25,rij:30,diepte:1,voor:[],zaai:[4,5,6],uit:[],oogst:[6,7,8],duur:60,moeite:'makkelijk',vrienden:['kool','ui','komkommer','sla','bloemkool','asperge'],vijanden:['wortel'],tip:'Lokt sluipwespen en zweefvliegen die luizen opruimen.',zorg:'Zaai op een vaste plek, dille laat zich slecht verplanten.'},
{id:'kamille',naam:'Kamille',lat:'Matricaria',type:'kruid',fam:'bloem',loc:'openlucht',zon:'zon',water:'laag',afstand:20,rij:25,diepte:1,voor:[],zaai:[3,4],uit:[],oogst:[6,7,8],duur:70,moeite:'makkelijk',vrienden:['kool','ui','spruitkool','bloemkool','boerenkool','broccoli'],vijanden:[],tip:'De "dokter van de tuin": versterkt buurplanten.',zorg:'Zaait zichzelf graag uit; laat een paar planten in bloei staan voor volgend jaar.'},
{id:'koriander',naam:'Koriander',lat:'Coriandrum sativum',type:'kruid',fam:'kruid',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:15,rij:25,diepte:1,voor:[],zaai:[4,5,6,7],uit:[],oogst:[6,7,8],duur:50,moeite:'gemiddeld',vrienden:['spinazie','komkommer','anijs'],vijanden:['venkel'],tip:'Trekt bestuivers; zet niet bij venkel.',zorg:'Schiet snel door in hitte, zaai bij voorkeur koel en bij vocht.'},
{id:'munt',naam:'Munt',lat:'Mentha',type:'kruid',fam:'kruid',loc:'beide',zon:'halfschaduw',water:'hoog',afstand:30,rij:30,diepte:1,voor:[],zaai:[],uit:[4,5],oogst:[5,6,7,8,9],duur:60,moeite:'makkelijk',vrienden:['kool','tomaat'],vijanden:[],tip:'Weert het koolwitje en luis.',zorg:'Zet in een pot of ingegraven emmer, munt woekert anders door de hele tuin.',rassen:[{naam:'Pepermunt',type:'pepermunt',kort:'Sterk mentol, fijn voor thee.'},{naam:'Kruizemunt',type:'groene munt',kort:'Mild, voor thee en gerechten.'},{naam:'Marokkaanse munt',type:'theemunt',kort:'Klassiek voor verse muntthee.'},{naam:'Chocolademunt',type:'chocolademunt',kort:'Zachte chocoladetoon.'}]},
{id:'oregano',naam:'Oregano',lat:'Origanum vulgare',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'laag',afstand:25,rij:30,diepte:1,voor:[],zaai:[4,5],uit:[],oogst:[6,7,8,9],duur:80,moeite:'makkelijk',vrienden:['tomaat','kool','paprika'],vijanden:[],tip:'Trekt bestuivers en is een goede bodembedekker.',zorg:'Vaste plant die van droge, schrale grond houdt, niet te veel water.'},
{id:'peterselie',naam:'Peterselie',lat:'Petroselinum crispum',type:'kruid',fam:'kruid',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:15,rij:25,diepte:1,voor:[],zaai:[3,4,5,6,7],uit:[],oogst:[5,6,7,8,9,10,11],duur:80,moeite:'makkelijk',vrienden:['tomaat','wortel','asperge','paprika'],vijanden:['sla','selderij'],tip:'Lokt nuttige insecten; niet bij sla zetten.',zorg:'Kiemt traag (3–4 weken). Houd de grond bij het kiemen constant vochtig.',rassen:[{naam:'Krulpeterselie',type:'krulpeterselie',kort:'Decoratief en mild.'},{naam:'Platte peterselie',type:'platte peterselie',kort:'Voller van smaak, Italiaans.'}]},
{id:'rozemarijn',naam:'Rozemarijn',lat:'Salvia rosmarinus',type:'kruid',fam:'kruid',loc:'beide',zon:'zon',water:'laag',afstand:50,rij:50,diepte:1,voor:[],zaai:[],uit:[5],oogst:[1,2,3,4,5,6,7,8,9,10,11,12],duur:0,moeite:'gemiddeld',vrienden:['kool','boon','wortel'],vijanden:[],tip:'Weert de wortelvlieg en het koolwitje.',zorg:'Vorstgevoelig, zet op een beschutte plek of overwinter in een pot binnen.'},
{id:'salie',naam:'Salie',lat:'Salvia officinalis',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'laag',afstand:40,rij:40,diepte:1,voor:[],zaai:[],uit:[5],oogst:[5,6,7,8,9,10],duur:0,moeite:'makkelijk',vrienden:['kool','wortel'],vijanden:['komkommer'],tip:'Weert de koolvlieg en wortelvlieg.',zorg:'Vaste plant; snoei in het voorjaar terug en geef droge, doorlatende grond.'},
{id:'tijm',naam:'Tijm',lat:'Thymus vulgaris',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'laag',afstand:25,rij:25,diepte:1,voor:[],zaai:[4,5],uit:[],oogst:[1,2,3,4,5,6,7,8,9,10,11,12],duur:0,moeite:'makkelijk',vrienden:['kool','aubergine'],vijanden:[],tip:'Weert het koolwitje en trekt bijen.',zorg:'Houdt van arme, droge grond. Te veel water is de grootste vijand.',rassen:[{naam:'Gewone tijm',type:'keukentijm',kort:'Het klassieke keukenkruid.'},{naam:'Citroentijm',type:'citroentijm',kort:'Frisse citrustoon.'},{naam:'Kruiptijm',type:'kruiptijm',kort:'Bodembedekker, ook tussen tegels.'}]},
{id:'borage',naam:'Borage',lat:'Borago officinalis',type:'kruid',fam:'bloem',loc:'openlucht',zon:'zon',water:'matig',afstand:40,rij:45,diepte:2,voor:[],zaai:[4,5],uit:[],oogst:[6,7,8],duur:55,moeite:'makkelijk',vrienden:['aardbei','courgette','tomaat'],vijanden:[],tip:'Lokt bijen en levert sporenelementen aan de grond.',zorg:'Zaait zichzelf rijkelijk uit; geef ruimte want hij wordt fors.'},
{id:'goudsbloem',naam:'Goudsbloem',lat:'Tagetes / Calendula',type:'kruid',fam:'bloem',loc:'openlucht',zon:'zon',water:'laag',afstand:30,rij:30,diepte:1,voor:[],zaai:[4,5],uit:[],oogst:[6,7,8,9,10],duur:60,moeite:'makkelijk',vrienden:['tomaat','kool','rode & zwarte bes','framboos','braam'],vijanden:[],tip:'Weert wortelaaltjes uit de grond en houdt witte vlieg klein.',zorg:'Pluk uitgebloeide bloemen weg voor doorbloei het hele seizoen.'},
{id:'oikers',naam:'O.I. kers',lat:'Tropaeolum majus',type:'kruid',fam:'bloem',loc:'openlucht',zon:'halfschaduw',water:'laag',afstand:30,rij:35,diepte:2,voor:[],zaai:[5],uit:[],oogst:[6,7,8,9,10],duur:60,moeite:'makkelijk',vrienden:['kool','boon','courgette','fruit','pompoen','tomaat','radijs'],vijanden:[],tip:'Vanglokker: trekt luis weg van je groenten. Blad en bloem zijn eetbaar.',zorg:'Arme grond geeft juist meer bloei; op vette grond vooral blad.'},
{id:'hysop',naam:'Hysop',lat:'Hyssopus officinalis',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'laag',afstand:30,rij:30,diepte:1,voor:[],zaai:[4,5],uit:[],oogst:[6,7,8,9],duur:0,moeite:'makkelijk',vrienden:['druif','kool'],vijanden:['radijs'],tip:'Trekt bijen en weert het koolwitje. Zet niet naast radijs.',zorg:'Vaste plant die van droge, kalkrijke grond houdt; snoei in het voorjaar.'},
{id:'kervel',naam:'Kervel',lat:'Anthriscus cerefolium',type:'kruid',fam:'kruid',loc:'openlucht',zon:'halfschaduw',water:'matig',afstand:15,rij:15,diepte:1,voor:[],zaai:[3,4,8,9],uit:[],oogst:[5,6,10],duur:40,moeite:'makkelijk',vrienden:['kruisbes','sla','radijs'],vijanden:[],tip:'Lokt nuttige insecten en verdraagt schaduw goed.',zorg:'Schiet snel door in de volle zon; zaai koel en regelmatig bij.'},
{id:'anijs',naam:'Anijs',lat:'Pimpinella anisum',type:'kruid',fam:'kruid',loc:'openlucht',zon:'zon',water:'matig',afstand:20,rij:20,diepte:1,voor:[],zaai:[4,5],uit:[],oogst:[8,9],duur:120,moeite:'gemiddeld',vrienden:['koriander'],vijanden:['wortel'],tip:'Trekt bestuivers en combineert goed met koriander.',zorg:'Heeft een lang, warm seizoen nodig; zaai op een beschutte plek.'}
];

/* category glyphs */
const GLY={
 vrucht:'<path d="M12 3c2.5 1 4 3 4 6 0 4-2.2 8-4 8s-4-4-4-8c0-3 1.5-5 4-6z"/><path d="M12 3c0-1 .8-1.8 2-2"/>',
 knol:'<ellipse cx="12" cy="13" rx="6.5" ry="5"/><circle cx="9.5" cy="12" r=".7" fill="currentColor" stroke="none"/><circle cx="13.5" cy="14" r=".7" fill="currentColor" stroke="none"/>',
 wortel:'<path d="M12 21c-1.5-3-2.5-7-2.5-10.5C9.5 8 10.5 6.5 12 6.5s2.5 1.5 2.5 4C14.5 14 13.5 18 12 21z"/><path d="M12 6.5l-2-2.5M12 6.5l1.8-2.6M12 6.5V3"/>',
 ui:'<path d="M12 21c-3 0-5-2.2-5-5 0-3.2 2.6-7 5-7s5 3.8 5 7c0 2.8-2 5-5 5z"/><path d="M12 9V4M12 9l-2-3M12 9l2-3"/>',
 blad:'<path d="M5 19C5 11 11 5 19 5c0 8-6 14-14 14z"/><path d="M5 19C8 16 12 12 16 8"/>',
 peul:'<path d="M6 18C4 13 8 5 16 6c2 5-2 13-10 12z"/><circle cx="9.5" cy="13" r="1"/><circle cx="11.5" cy="11" r="1"/><circle cx="13.5" cy="9" r="1"/>',
 kool:'<circle cx="12" cy="13" r="6"/><path d="M12 7c-2 2-3.5 4-3.5 6M12 7c2 2 3.5 4 3.5 6M7 11c2 .5 3.5 1.5 5 4M17 11c-2 .5-3.5 1.5-5 4"/>',
 fruit:'<path d="M12 21c-3.2 0-5.5-2.4-5.5-5.5C6.5 12 9 10 12 10s5.5 2 5.5 5.5C17.5 18.6 15.2 21 12 21z"/><path d="M12 10c0-2 1.2-3.5 3.2-4M12 10c-1-1.6-3-2-4.6-1.4"/>',
 struik:'<path d="M12 20v-7M12 13l-3-3M12 16l3-3M12 13l3-2.5M9 10c-2 0-3.5-1.5-3.5-3.5C7.5 6.5 9 8 9 10zM15 10.5c2 0 3.5-1.5 3.5-3.5C16.5 7 15 8.5 15 10.5z"/>',
 kruid:'<path d="M12 21v-9M12 12c0-3 2-5 5-5 0 3-2 5-5 5zM12 14c0-3-2-5-5-5 0 3 2 5 5 5z"/>',
 bloem:'<circle cx="12" cy="12" r="2.2"/><path d="M12 9.8V6M12 14.2V18M9.8 12H6M14.2 12H18M10.3 10.3 7.8 7.8M13.7 13.7l2.5 2.5M13.7 10.3l2.5-2.5M10.3 13.7l-2.5 2.5"/>',
};
function gicon(fam){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">'+(GLY[fam]||GLY.blad)+'</svg>';}

/* synonym map: companion label -> plant id */
const SYN={'wortel':'wortel','peen':'wortel','wortel / peen':'wortel','stamboon':'boon','stokboon':'boon','boon':'boon','stam- / stokboon':'boon','ui':'ui','doperwt':'doperwt','erwt':'doperwt','biet':'biet','rode biet':'biet','kool':'kool','o.i. kers':'oikers','oost-indische kers':'oikers','borage':'borage','komkommerkruid':'borage','sla':'sla','tomaat':'tomaat','aardbei':'aardbei','goudsbloem':'goudsbloem','bieslook':'bieslook','knoflook':'knoflook','look':'knoflook','prei':'prei','mais':'mais','komkommer':'komkommer','spinazie':'spinazie','radijs':'radijs','selderij':'selderij','venkel':'venkel','paprika':'paprika','aardappel':'aardappel','pompoen':'pompoen','dille':'dille','kamille':'kamille','bonenkruid':'bonenkruid','basilicum':'basilicum','courgette':'courgette','andijvie':'andijvie','pastinaak':'pastinaak','rabarber':'rabarber','framboos':'framboos','braam':'braam','peterselie':'peterselie','munt':'munt','oregano':'oregano','rozemarijn':'rozemarijn','salie':'salie','tijm':'tijm','mierikswortel':'mierikswortel','hysop':'hysop','kervel':'kervel','asperge':'asperge','aubergine':'aubergine','anijs':'anijs','koolrabi':'koolrabi','bloemkool':'bloemkool','broccoli':'broccoli','boerenkool':'boerenkool','spruitkool':'spruitkool','spruitjes':'spruitkool','witlof':'witlof','snijbiet':'snijbiet','tuinboon':'tuinboon','rucola':'rucola','rode & zwarte bes':'bes','bes':'bes','kruisbes':'kruisbes','blauwe bes':'blauwebes','druif':'druif','tomaat dichtbij':'tomaat','braam dichtbij':'braam','framboos dichtbij':'framboos','kool dichtbij':'kool','venkel (knol)':'venkel','blauwebes':'blauwebes','koriander':'koriander','oikers':'oikers'};
function resolve(label){const k=label.toLowerCase().trim();return SYN[k]||null;}
const byId=id=>DATA.find(p=>p.id===id);

const TYPE_LABEL={groente:'Groente',fruit:'Fruit',kruid:'Kruid'};
const LOC_LABEL={openlucht:'Open lucht',kas:'Kas',beide:'Kas of buiten'};
const WATER_LABEL={laag:'Weinig water',matig:'Matig water',hoog:'Veel water'};
